### PR TITLE
Upgrade alpine & moving away from embedded mongo for tests

### PR DESCRIPTION
**Pull request by tosan88**

### CODE REVIEW

**Comment by tosan88** [comment]
@khatton-ft I did the changes, although I don't like how maven hides the skipped tests. I wouldn't have in mind to check if those tests were skipped or not, and I would assume they all run and finished with success.

**Comment by khatton-ft** [comment]
Hmm, yes I see what you mean @tosan88, it's easy to miss the report that tests were skipped. I suppose you _could_ add another environment var that mimicked the behaviour of Go's `go test -short` (in the ES service I think we have written them so that you can only omit the data store tests if you also choose to run with `-short`). Either way, you should probably add some description of this behaviour to the README.

**Comment by tosan88** [comment]
@khatton-ft I did some changes, hope it's ok

**Comment by khatton-ft** [comment]
Nice work, glad you got there in the end!

**Pull request merged**
